[project]
name = "scraper-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "httpx>=0.28.1",
    "markdownify>=1.2.0",
    "portia-sdk-python>=0.7.2",
]
