[tool.poetry]
name = "portia_outreach_agent"
version = "0.1.0"
description = "Outreach agent for Portia AI"
authors = ["Portia AI <hello@portialabs.ai>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
portia-sdk-python = {extras = ["tools-browser-local"], version = "^0.4.1"}
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"